import type { Metadata } from "next";

import "./globals.css";
import { Sider } from "./components/sider/Sider";
import  Search  from "./components/search/Search";
import  Play  from "./components/play/Play";
import icon from "../../public/logomusic.svg"
import { Suspense } from "react";
export const metadata: Metadata = {
  title: "Music web",
  description: "Generated by create next app",
  icons:{
    icon:
    {
      url:icon.src
    }
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#292929]">
        <div className="container mx-auto ">
          <div className="flex  ">
            <div className="w-[280px]">
              <Sider/>
            </div>
            <div className="flex-1 ml-[20px]">
              <Suspense>
              <Search/>
              </Suspense>
            
              <main className="mb-[120px] mt-[30px]">
              {children}
              </main>
            </div>
          </div>
        </div>
      <Play/>
      </body>
    </html>
  );
}
